// Nigerian tertiary institutions for the Anchor Club institution picker.
// Federal, state and private universities plus a few large polytechnics. The
// combobox still lets someone type an institution that isn't listed, so this
// doesn't need to be exhaustive — it just keeps the common names clean.

export const NIGERIAN_INSTITUTIONS: string[] = [
  // ── Federal universities ──
  "University of Lagos (UNILAG)",
  "University of Ibadan (UI)",
  "University of Ilorin (UNILORIN)",
  "University of Nigeria, Nsukka (UNN)",
  "University of Benin (UNIBEN)",
  "Obafemi Awolowo University (OAU)",
  "Ahmadu Bello University (ABU), Zaria",
  "University of Port Harcourt (UNIPORT)",
  "Bayero University Kano (BUK)",
  "University of Calabar (UNICAL)",
  "University of Jos (UNIJOS)",
  "University of Maiduguri (UNIMAID)",
  "University of Abuja (UNIABUJA)",
  "Federal University of Technology, Akure (FUTA)",
  "Federal University of Technology, Minna (FUTMINNA)",
  "Federal University of Technology, Owerri (FUTO)",
  "Michael Okpara University of Agriculture, Umudike",
  "Federal University of Agriculture, Abeokuta (FUNAAB)",
  "Nnamdi Azikiwe University (UNIZIK), Awka",
  "University of Uyo (UNIUYO)",
  "University of Agriculture, Makurdi (Joseph Sarwuan Tarka University)",
  "Usmanu Danfodiyo University, Sokoto (UDUS)",
  "Federal University, Oye-Ekiti (FUOYE)",
  "Federal University, Dutse",
  "Federal University, Lafia",
  "Federal University, Lokoja",
  "Federal University, Kashere",
  "Federal University, Wukari",
  "Federal University, Dutsin-Ma",
  "Federal University, Gashua",
  "Federal University, Gusau",
  "Federal University, Birnin Kebbi",
  "Federal University, Otuoke",
  "Federal University, Ndufu-Alike Ikwo (AE-FUNAI)",
  "Modibbo Adama University, Yola (MAU)",
  "Nigerian Defence Academy (NDA), Kaduna",
  "National Open University of Nigeria (NOUN)",
  "Alex Ekwueme Federal University, Ndufu-Alike",
  "Federal University of Petroleum Resources, Effurun (FUPRE)",
  "Nigeria Maritime University, Okerenkoko",
  "Air Force Institute of Technology, Kaduna",

  // ── State universities ──
  "Lagos State University (LASU)",
  "Ekiti State University (EKSU)",
  "Rivers State University (RSU)",
  "Enugu State University of Science and Technology (ESUT)",
  "Delta State University (DELSU), Abraka",
  "Ambrose Alli University (AAU), Ekpoma",
  "Olabisi Onabanjo University (OOU), Ago-Iwoye",
  "Ladoke Akintola University of Technology (LAUTECH), Ogbomoso",
  "Osun State University (UNIOSUN)",
  "Kwara State University (KWASU), Malete",
  "Kaduna State University (KASU)",
  "Nasarawa State University, Keffi",
  "Benue State University, Makurdi",
  "Imo State University (IMSU), Owerri",
  "Abia State University (ABSU), Uturu",
  "Ebonyi State University (EBSU), Abakaliki",
  "Cross River University of Technology (CRUTECH)",
  "Akwa Ibom State University (AKSU)",
  "Bauchi State University, Gadau",
  "Gombe State University",
  "Yobe State University, Damaturu",
  "Kano University of Science and Technology, Wudil",
  "Sokoto State University",
  "Kebbi State University of Science and Technology, Aliero",
  "Ignatius Ajuru University of Education, Port Harcourt",
  "Tai Solarin University of Education, Ijagun",
  "Adekunle Ajasin University, Akungba (AAUA)",
  "Bayelsa Medical University",
  "Niger Delta University, Wilberforce Island",
  "Chukwuemeka Odumegwu Ojukwu University (COOU)",
  "Sule Lamido University, Kafin Hausa",
  "Umaru Musa Yar'adua University, Katsina",
  "Plateau State University, Bokkos",
  "Taraba State University, Jalingo",
  "Kogi State University, Anyigba (Prince Abubakar Audu University)",
  "Ondo State University of Science and Technology, Okitipupa",
  "Oyo State Technical University, Ibadan (First Technical University)",
  "Moshood Abiola Polytechnic, Abeokuta",
  "Yaba College of Technology (YABATECH)",
  "Auchi Polytechnic",
  "The Polytechnic, Ibadan",

  // ── Private universities ──
  "Covenant University, Ota",
  "Babcock University, Ilishan-Remo",
  "Afe Babalola University, Ado-Ekiti (ABUAD)",
  "Bowen University, Iwo",
  "Landmark University, Omu-Aran",
  "Redeemer's University, Ede",
  "Bells University of Technology, Ota",
  "Pan-Atlantic University, Lagos",
  "American University of Nigeria, Yola (AUN)",
  "Bingham University, Karu",
  "Lead City University, Ibadan",
  "Caleb University, Lagos",
  "Crawford University, Igbesa",
  "Elizade University, Ilara-Mokin",
  "Nile University of Nigeria, Abuja",
  "Baze University, Abuja",
  "Augustine University, Ilara",
  "Mountain Top University, Prayer City",
  "Chrisland University, Abeokuta",
  "Hallmark University, Ijebu-Itele",
  "Adeleke University, Ede",
  "Achievers University, Owo",
  "Wellspring University, Benin City",
  "Igbinedion University, Okada",
  "Madonna University, Okija",
  "Renaissance University, Ugbawka",
  "Gregory University, Uturu",
  "Novena University, Ogume",
  "Western Delta University, Oghara",
  "Salem University, Lokoja",
  "Veritas University, Abuja",
  "Kwararafa University, Wukari",
  "Al-Hikmah University, Ilorin",
  "Fountain University, Osogbo",
  "Crescent University, Abeokuta",
  "Ajayi Crowther University, Oyo",
  "Joseph Ayo Babalola University, Ikeji-Arakeji",
  "McPherson University, Seriki-Sotayo",
  "Southwestern University, Okun-Owa",
  "Kings University, Ode-Omu",
  "Dominion University, Ibadan",
  "Precious Cornerstone University, Ibadan",
  "Coal City University, Enugu",
  "Godfrey Okoye University, Enugu",
  "Rhema University, Aba",
  "Clifford University, Owerrinta",
  "Spiritan University, Nneochi",
  "Evangel University, Akaeze",
  "Paul University, Awka",
  "Tansian University, Umunya",
  "Edwin Clark University, Kiagbodo",
  "Michael and Cecilia Ibru University, Agbarha-Otor",
  "Glorious Vision University, Ogwa",
  "Wesley University, Ondo",
  "Summit University, Offa",
  "Thomas Adewumi University, Oko",
  "Skyline University Nigeria, Kano",
  "Khadija University, Majia",
  "Al-Qalam University, Katsina",
  "Legacy University, Okija",
  "PAMO University of Medical Sciences, Port Harcourt",
  "Eko University of Medicine and Health Sciences, Ijanikin",
  "Trinity University, Lagos",
  "Anchor University, Lagos",
  "Mountcrest University, Lagos",
  "Christopher University, Mowe",
  "Dominican University, Ibadan",
  "Atiba University, Oyo",
  "Arthur Jarvis University, Akpabuyo",
  "Greenfield University, Kaduna",
  "Franco British International University, Kaduna",
  "Maryam Abacha American University, Kano",
  "Nok University, Kachia",
];

// Level of study — 100 through 500 plus common extras.
export const STUDY_LEVELS: string[] = [
  "100 Level",
  "200 Level",
  "300 Level",
  "400 Level",
  "500 Level",
  "600 Level",
  "ND / HND",
  "Postgraduate",
  "Recent graduate",
];
