import type { Metadata } from "next";
import { SITE } from "./constants";

const title = "Klario — Your Money, Finally Making Sense for Nigerians";
const description =
  "Klario is an AI-powered personal finance app for Nigerians. Connect every bank, track spending with AI, automate savings, and pay bills, all in one place.";

export const siteMetadata: Metadata = {
  metadataBase: new URL("https://klario.finance"),
  title: {
    default: title,
    template: `%s · ${SITE.name}`,
  },
  description,
  applicationName: SITE.name,
  authors: [{ name: SITE.legalName }],
  creator: SITE.legalName,
  publisher: SITE.legalName,
  category: "Finance",
  keywords: [
    "Klario",
    "Klario Finance",
    "Klario Nigeria",
    "Klario app",
    "Klario AI",
    "KlarioAI",
    "Klario fintech",
    "Klario Raavon Limited",
    "Klario money",
    "Klario money manager",
    "Klario download",
    "Klario waitlist",
    "klario.finance",
    "klar",
    "klar app",
    "klar finance",
    "fintech",
    "fintech Nigeria",
    "Nigerian fintech",
    "fintech app Nigeria",
    "finance",
    "finance app",
    "finance app Nigeria",
    "financial",
    "financial app",
    "financial app Nigeria",
    "financial assistance",
    "financial assistant",
    "AI financial assistant",
    "financial manager",
    "financial manager app",
    "financial manager Nigeria",
    "financial advisor",
    "financial advisor Nigeria",
    "financial planning",
    "financial planning Nigeria",
    "financial intelligence",
    "financial intelligence platform",
    "financial coach",
    "financial wellness",
    "personal finance",
    "personal finance Nigeria",
    "personal finance app",
    "personal finance app Nigeria",
    "personal finance manager",
    "personal finance management",
    "PFM Nigeria",
    "money management",
    "money manager",
    "money manager Nigeria",
    "money manager app",
    "money tracking Nigeria",
    "budgeting",
    "budgeting app",
    "budgeting app Nigeria",
    "Naira budgeting",
    "savings app",
    "savings app Nigeria",
    "automated savings Nigeria",
    "bill payment Nigeria",
    "airtime payment Nigeria",
    "bank account tracker Nigeria",
    "multiple bank accounts Nigeria",
    "open banking Nigeria",
    "AI finance",
    "AI finance Nigeria",
    "AI personal finance",
    "AI money manager",
  ],
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title,
    description,
    url: "https://klario.finance",
    siteName: SITE.legalName,
    type: "website",
    locale: "en_NG",
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: `${SITE.name}: ${SITE.tagline}`,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
    images: ["/opengraph-image"],
    site: SITE.twitter,
    creator: SITE.twitter,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  icons: {
    icon: "/favicon.ico",
    apple: "/favicon.ico",
  },
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
};
